USE BIO_DB;
DROP TABLE IF EXISTS quotes;
CREATE TABLE IF NOT EXISTS quotes(
    author
);
DESCRIBE quotes;

DROP TABLE IF EXISTS pets;
CREATE TABLE IF NOT EXISTS pets(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(15) NOT NULL,
    PRIMARY KEY(id)

);
DESCRIBE pets;